export const arrowBack = document.getElementById("back-mode-button");
export const weatherContent = document.getElementById("info-content");
export const alerts = document.querySelectorAll(".alert");
export const cityInput = document.querySelector("input");
export const geoLocationBtn = document.querySelector("button");
export const weatherImg = document.querySelector("img");
export const weatherTemp = document.querySelector(".degree");
export const weatherKind = document.querySelector(".weather-kind");
export const cityName = document.querySelector("#city-name");
export const subDegree = document.querySelector(".sub-tem-span");
export const humbPercent = document.querySelector(".hum-precent"); //You have to call for its FirstElementChild
